- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 25200 #7 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsGlovesLatex
    eyes: ClothingEyesGlassesMed
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: TelescopicBaton
  storage:
    back:
    - BoxSurvivalBrigmedic
    - Flash
    - MagazinePistolRubber
    - Cautery
