- type: latheRecipe
  id: Handcuffs
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  result: Handcuffs
  completetime: 2
  materials:
    Steel: 300

- type: latheRecipe
  id: Zipties
  icon:
    sprite: Objects/Misc/zipties.rsi
    state: cuff
  result: Zipties
  completetime: 2
  materials:
    Plastic: 200

- type: latheRecipe
  id: Stunbaton
  icon:
    sprite: Objects/Weapons/Melee/stunbaton.rsi
    state: stunbaton_off
  result: Stunbaton
  completetime: 2
  materials:
    Steel: 300
    Plastic: 300

- type: latheRecipe
  id: ForensicPad
  icon:
    sprite: Objects/Misc/bureaucracy.rsi
    state: paper
  result: ForensicPad
  completetime: 4
  materials:
    Plastic: 100

- type: latheRecipe
  id: ClothingEyesGlassesSecurity
  icon:
    sprite: Clothing/Eyes/Glasses/secglasses.rsi
    state: icon
  result: ClothingEyesGlassesSecurity
  completetime: 2
  materials:
    Steel: 300
    Glass: 200

- type: latheRecipe
  id: RiotShield
  icon:
    sprite: Objects/Weapons/Melee/shields.rsi
    state: riot-icon
  result: RiotShield
  completetime: 4
  materials:
    Steel: 400
    Glass: 400

- type: latheRecipe
  id: Flash
  icon:
    sprite: Objects/Weapons/Melee/flash.rsi
    state: flash
  result: Flash
  completetime: 2
  materials:
    Glass: 100
    Plastic: 200
    Steel: 100

- type: latheRecipe
  id: ShellShotgunBeanbag
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: beanbag
  result: ShellShotgunBeanbag
  completetime: 2
  materials:
    Plastic: 15
    Steel: 10

- type: latheRecipe
  id: CartridgePistolRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistolRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnumRubber
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeCaselessRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeCaselessRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeLightRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLightRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeRifleRubber
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgePistol
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgePistol
  completetime: 2
  materials:
    Steel: 10

- type: latheRecipe
  id: ShellShotgun
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: base
  result: ShellShotgun
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeMagnum
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeMagnum
  completetime: 2
  materials:
    Steel: 20

- type: latheRecipe
  id: CartridgeLightRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/ammo_casing.rsi
    state: base
  result: CartridgeLightRifle
  completetime: 2
  materials:
    Steel: 30

- type: latheRecipe
  id: ShellShotgunFlare
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: flare
  result: ShellShotgunFlare
  completetime: 2
  materials:
    Plastic: 20
    Steel: 5

- type: latheRecipe
  id: ShellTranquilizer
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Casings/shotgun_shell.rsi
    state: practice
  result: ShellTranquilizer
  completetime: 4
  materials:
    Plastic: 15
    Steel: 10
    Glass: 5

- type: latheRecipe
  id: TargetHuman
  icon:
    sprite: Objects/Specific/Security/target.rsi
    state: target_h
  result: TargetHuman
  completetime: 5
  materials:
    Steel: 10

- type: latheRecipe
  id: TargetClown
  icon:
    sprite: Objects/Specific/Security/target.rsi
    state: target_c
  result: TargetClown
  completetime: 5
  materials:
    Steel: 10

- type: latheRecipe
  id: TargetSyndicate
  icon:
    sprite: Objects/Specific/Security/target.rsi
    state: target_s
  result: TargetSyndicate
  completetime: 5
  materials:
    Steel: 10

# Magazines for SecurityTechFab and WeaponsTechFab
# Resource logic. [Number of rounds in magazine]*[Cartridge material] + 100 steel
# Complete time logic. [Number of rounds in magazine]*[Cartridge complete time] + 5
- type: latheRecipe
  id: MagazinePistolRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pistol_mag.rsi
    state: rubber
  result: MagazinePistolRubber
  completetime: 25
  materials:
    Plastic: 50
    Steel: 150

- type: latheRecipe
  id: MagazineMagnumRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_mag.rsi
    state: rubber
  result: MagazineMagnumRubber
  completetime: 25
  materials:
    Plastic: 50
    Steel: 150

- type: latheRecipe
  id: MagazineCaselessRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/CaselessRifle/caseless_rifle_mag.rsi
    state: rubber
  result: MagazineCaselessRifleRubber
  completetime: 65
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineLightRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_mag.rsi
    state: rubber
  result: MagazineLightRifleRubber
  completetime: 65
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineRifleRubber
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: rubber
  result: MagazineRifleRubber
  completetime: 55
  materials:
    Plastic: 250
    Steel: 225

- type: latheRecipe
  id: MagazinePistol
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Pistol/pistol_mag.rsi
    state: red
  result: MagazinePistol
  completetime: 25
  materials:
    Steel: 200

- type: latheRecipe
  id: MagazineMagnum
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Magnum/magnum_mag.rsi
    state: red
  result: MagazineMagnum
  completetime: 25
  materials:
    Steel: 300

- type: latheRecipe
  id: MagazineCaselessRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/CaselessRifle/caseless_rifle_mag.rsi
    state: red
  result: MagazineCaselessRifle
  completetime: 65
  materials:
    Plastic: 300
    Steel: 250

- type: latheRecipe
  id: MagazineLightRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/LightRifle/light_rifle_mag.rsi
    state: red
  result: MagazineLightRifle
  completetime: 65
  materials:
    Steel: 1000

- type: latheRecipe
  id: MagazineRifle
  icon:
    sprite: Objects/Weapons/Guns/Ammunition/Magazine/Rifle/rifle_mag.rsi
    state: red
  result: MagazineRifle
  completetime: 55
  materials:
    Plastic: 250
    Steel: 225
# Magazines for SecurityTechFab
# Weapons kinetic
- type: latheRecipe
  id: WeaponRevolverInspector
  icon:
    sprite: Objects/Weapons/Guns/Revolvers/inspector.rsi
    state: icon
  result: WeaponRevolverInspector
  completetime: 30
  materials:
    Steel: 500

- type: latheRecipe
  id: WeaponSubMachineGunWt550
  icon:
    sprite: Objects/Weapons/Guns/SMGs/wt550.rsi
    state: base
  result: WeaponSubMachineGunWt550
  completetime: 75
  materials:
    Plastic: 200
    Steel: 1000

- type: latheRecipe
  id: WeaponRifleLecter
  icon:
    sprite: Objects/Weapons/Guns/Rifles/lecter.rsi
    state: base
  result: WeaponRifleLecter
  completetime: 90
  materials:
    Plastic: 200
    Steel: 1300

- type: latheRecipe
  id: WeaponShotgunDoubleBarreled
  icon:
    sprite: Objects/Weapons/Guns/Shotguns/db_shotgun.rsi
    state: icon
  result: WeaponShotgunDoubleBarreled
  completetime: 60
  materials:
    Wood: 500
    Steel: 500

- type: latheRecipe
  id: WeaponRifleAk
  icon:
    sprite: Objects/Weapons/Guns/Rifles/ak.rsi
    state: base
  result: WeaponRifleAk
  completetime: 75
  materials:
    Wood: 200
    Steel: 1000

- type: latheRecipe
  id: WeaponPistolMk58
  icon:
    sprite: Objects/Weapons/Guns/Pistols/mk58.rsi
    state: base
  result: WeaponPistolMk58
  completetime: 30
  materials:
    Steel: 500

- type: latheRecipe
  id: WeaponSubMachineGunVector
  icon:
    sprite: Objects/Weapons/Guns/SMGs/vector.rsi
    state: base
  result: WeaponSubMachineGunVector
  completetime: 60
  materials:
    Plastic: 200
    Steel: 800

# Weapons energy
- type: latheRecipe
  id: WeaponDisabler
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  result: WeaponDisabler
  completetime: 35
  materials:
    Glass: 300
    Steel: 300

- type: latheRecipe
  id: WeaponDisablerPractice
  icon:
    sprite: Objects/Weapons/Guns/Battery/practice_disabler.rsi
    state: base
  result: WeaponDisablerPractice
  completetime: 25
  materials:
    Glass: 200
    Steel: 200

- type: latheRecipe
  id: WeaponLaserCarbine
  icon:
    sprite: Objects/Weapons/Guns/Battery/laser_gun.rsi
    state: base
  result: WeaponLaserCarbine
  completetime: 90
  materials:
    Glass: 500
    Plastic: 500
    Steel: 500

