- type: job
  id: Miner
  name: job-name-miner
  description: job-description-miner
  playTimeTracker: JobMiner
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 108000 #30 hrs
  icon: "JobIconShaftMiner"
  startingGear: MinerGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: MinerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMiner
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: MinerPDA
    ears: ClothingHeadsetMining
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
