- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 72000
  weight: 10
  startingGear: QuartermasterGear
  icon: "QuarterMaster"
  supervisors: job-supervisors-hop
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatQMsoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    pocket1: AppraisalTool
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
