- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: GarmentBagWarden
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurity
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitWarden
      - id: HoloprojectorSecurity

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingOuterArmorBasic
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: HoloprojectorSecurity
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HoloprojectorSecurity
        prob: 0.6

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesHudMedSec
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 4
      - id: ClothingOuterHardsuitBrigmedic
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingHandsGlovesNitrile
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpsuitBrigmedicTurtle
      - id: ClothingUniformJumpskirtBrigmedicTurtle
      - id: ClothingOuterCoatBrigmedicWB
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
      - id: BoxSyringe
      - id: BoxPillCanister
      - id: BoxBodyBag
      - id: EpinephrineChemistryBottle
        amount: 1

- type: entity
  id: LockerBrigmedicFilled
  suffix: Filled
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesHudMedSec
      - id: TrackingImplanter
        amount: 4
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingHandsGlovesNitrile
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpsuitBrigmedicTurtle
      - id: ClothingUniformJumpskirtBrigmedicTurtle
      - id: ClothingOuterCoatBrigmedicWB
      - id: MedkitCombatFilled
      - id: MedkitAdvancedFilled
      - id: BoxSyringe
      - id: BoxPillCanister
      - id: BoxBodyBag
      - id: EpinephrineChemistryBottle
        amount: 1

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
        prob: 0.3
      - id: ClothingHeadHatFedoraBrown
      - id: ClothingNeckTieDet
      - id: ClothingOuterVestDetective
      - id: ClothingOuterCoatDetective
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      # NT is cheap, what can you do...
      - id: Wirecutter
        prob: 0.9
      - id: Screwdriver
        prob: 0.9
      - id: Multitool
        prob: 0.5

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: BoxLethalshot
      amount: 2

- type: entity
  parent: GunSafe
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: BoxShotgunIncendiary
      amount: 1
    - id: BoxLethalshot
      amount: 1

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: GunSafe
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3
